import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const base = process.env.ARCADIA_TEST_URL || 'http://127.0.0.1:5174';
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'chrome', headless: true });
try {
  const context = await browser.newContext();
  const page = await context.newPage();
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(base);
  await page.getByRole('button', { name: /I am a caretaker/ }).click();
  await page.getByLabel('Your name').fill('Test Caregiver');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByText('Caregiver Dashboard', { exact: true }).waitFor();
  assert.match(page.url(), /\/caregiver/);
  assert.equal(await page.locator('a a').count(), 0, 'No nested links');
  await page.getByTestId('button-add-reminder-preview').click();
  await page.getByTestId('input-reminder-title').fill('Integration test reminder');
  await page.getByTestId('input-reminder-notes').fill('Test notes');
  await page.getByTestId('button-save-reminder').click();
  let reminder = page.locator('article').filter({ hasText: 'Integration test reminder' });
  await reminder.waitFor();
  await page.reload();
  await reminder.waitFor();
  await reminder.getByRole('button', { name: 'Edit reminder', exact: true }).click();
  await page.getByTestId('input-reminder-title').fill('Updated test reminder');
  await page.getByTestId('input-reminder-notes').fill('');
  await page.getByTestId('button-save-reminder').click();
  reminder = page.locator('article').filter({ hasText: 'Updated test reminder' });
  await reminder.getByRole('button', { name: 'Pause reminder' }).click();
  await reminder.getByRole('button', { name: 'Resume', exact: true }).click();
  await reminder.getByRole('button', { name: 'Completed', exact: true }).click();
  await page.getByTestId('button-back').click();
  await page.getByTestId('card-connect').click();
  await page.getByTestId('button-add-contact-family').click();
  await page.getByTestId('input-contact-name').fill('Test contact');
  await page.getByTestId('input-contact-phone').fill('0000000000');
  await page.getByTestId('button-save-contact').click();
  await page.getByText('Test contact', { exact: true }).waitFor();
  await page.reload();
  await page.getByText('Test contact', { exact: true }).waitFor();
  await page.getByTestId('button-back').click();
  await page.getByTestId('card-medical-reports').click();
  await page.getByTestId('button-upload-record').click();
  await page.getByTestId('input-record-title').fill('Test record');
  await page.getByTestId('input-record-date').fill('12/09/2026');
  await page.getByTestId('button-save-record').click();
  await page.reload();
  await page.getByText('Test record', { exact: true }).waitFor();
  await page.getByTestId('button-back').click();
  await page.getByRole('link', { name: 'View Profile →' }).click();
  await page.getByTestId('button-edit-field-name').click();
  await page.getByTestId('input-field-name').fill('Test Elder');
  await page.getByTestId('button-save-field-name').click();
  await page.getByTestId('button-back').click();
  await page.getByRole('heading', { name: 'Test Elder', exact: true }).waitFor();
  for (const [card, heading] of [['card-location-safety', 'Location & Safety'], ['card-daily-progress', 'Daily Progress'], ['card-medical-reports', 'Medical Reports'], ['card-alerts', 'Alerts & Notifications'], ['card-reminders', 'Reminders'], ['card-connect', 'Connect']]) {
    await page.getByTestId(card).click();
    await page.getByRole('heading', { name: heading, exact: true }).waitFor();
    await page.getByTestId('button-back').click();
  }
  await page.setViewportSize({ width: 375, height: 812 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true, 'Caregiver mobile layout fits');
  await page.screenshot({ path: '.test-runtime/caregiver-mobile.png', fullPage: true });
  await page.getByTestId('button-switch-user').click();
  await page.getByRole('button', { name: /I am here for myself/ }).click();
  await page.getByLabel('What should we call you?').fill('Test Patient');
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: /Family See your loved ones/ }).waitFor();
  assert.equal(await page.getByText('Caregiver Dashboard', { exact: true }).count(), 0);
  await page.goto(`${base}/caregiver`);
  await page.getByRole('button', { name: /Family See your loved ones/ }).waitFor();
  assert.equal(new URL(page.url()).pathname, '/');
  assert.deepEqual(errors, []);
  console.log('PASS: role separation, original dashboard pages, reminders add/edit/pause/resume/complete, contact persistence, profile edits, mobile width and no runtime errors.');
} finally { await browser.close(); }
